### ISSUE TITLE
Blurred image after crop

### ISSUE THREAD

**Issue by johannesdb** [joppuyo/acf-image-aspect-ratio-crop#106] opened 2022-03-29 15:27 UTC
When I crop an image on the server, the result is blurred compared to a version cropped on my computer:
Cropped on server:
![Cropped on webserver](https://user-images.githubusercontent.com/13348690/160646923-3e405054-0799-4426-a84a-547416dc4a45.jpeg)
Cropped on mac
![Cropped on mac](https://user-images.githubusercontent.com/13348690/160646936-678e273f-c425-4f3a-8e6e-5af26cee278a.jpeg)

I can see that others have similar issues:
https://stackoverflow.com/questions/56573339/using-cropper-js-image-quality-get-reduced-after-cropping

**Comment by joppuyo** [comment] 2022-04-30 15:45
Hey,

This plugin uses the WordPress image editing API for cropping images. The blurriness is caused by certain hard-coded values in the WordPress ImageMagick editor.

You could use the following code in your theme or a site-specific plugin to force WP into using GD API instead of ImageMagick:

```
add_filter( 'wp_image_editors', function( $editors ) {
        return ['WP_Image_Editor_GD' ];
});
```

I have also written a plugin that provides a modified version of the ImageMagick image editor class that doesn't have the same issue with blurring and smoothing the images. You can download it [here](https://github.com/joppuyo/imagemagick-extended). The plugin is still work in progress but it has the core functionality complete. I have used it on several production sites already to combat the image blurring issue.

**Comment by joppuyo** [comment] 2022-08-25 08:35
I'm closing this since the issue is not related to the plugin.

**Closed by joppuyo** 2022-08-25 08:35 UTC
