### ISSUE TITLE
When cropping an image, the crop button is not displayed

### ISSUE THREAD

**Issue by liu1435533520** [joppuyo/acf-image-aspect-ratio-crop#13] opened 2019-05-23 02:44 UTC
When the Gutenberg editor crops the image, the cropping window is too high and the cropping button is invisible and the button cannot be clicked.

**Comment by joppuyo** [comment] 2019-05-23 10:36
Hey, I'm unable to reproduce this. For me, the crop field works [correctly](https://raw.githubusercontent.com/joppuyo/acf-image-aspect-ratio-crop/master/assets/images/screenshot-1.jpg) in Gutenberg editor when the field is attached to the post or to a block.

Can you tell me the version of WordPress, ACF and ACF image aspect ratio crop plugin you are using?

Thanks!

**Comment by liu1435533520** [comment] 2019-05-28 07:37
Sorry, I can't reproduce this bug too. 

Thanks!

**Comment by joppuyo** [comment] 2019-05-28 08:07
Ok, great!

I'll close this issue.

Feel free to open another one if you run into this issue again.

**Closed by joppuyo** 2019-05-28 08:07 UTC
