### ISSUE TITLE
Does not work in Repeater

### ISSUE THREAD

**Issue by 1ucay** [joppuyo/acf-image-aspect-ratio-crop#6] opened 2018-07-23 21:19 UTC
In console of Chrome
acf-input.js
origCallback.apply is not a function

**Comment by joppuyo** [comment] 2018-07-23 21:52
Hey, thanks for reporting this issue.

I'm unfortunately unable to reproduce this problem in my end.

The field is working for me inside repeater without any issues.

<img width="932" alt="screen shot 2018-07-24 at 0 50 56" src="https://user-images.githubusercontent.com/1595438/43104927-babcfbd8-8edb-11e8-9e90-b6f531167cd2.png">

Could you give me the version of your **WordPress installation**, **Advanced Custom Fields** and **Image Aspect Ratio Crop** plugin? This way I can try to track the issue down.

Thanks!

**Comment by joppuyo** [comment] 2018-08-01 16:34
Hey @1ucay, I just run into this problem myself too.

It looks like an incompatibility with ACF 5.7. I'm working on a fix right now.

**Comment by joppuyo** [comment] 2018-08-01 16:45
Fixed in latest release v1.0.4

**Closed by joppuyo** 2018-08-01 16:45 UTC

**Comment by 1ucay** [comment] 2018-08-01 19:44
Thank you sir :+1:
